### ISSUE TITLE
Could not find org.grails.plugins:jasper:2.0.0.RC1

### ISSUE THREAD

**Issue by jmccordova** [puneetbehl/grails-jasper#5]
Following the documentation, it says there that I should put `compile "org.grails.plugins:jasper:2.0.0.RC1"` in build.gradle.

However, while compiling, this error shows up. Accessing https://repo.grails.org/grails/core/org/grails/plugins/ also tells you that there is no such thing as jasper.

**Comment by puneetbehl** [comment]
@jmccordova which version of Grails are you using? I can see the jar over bintray https://bintray.com/puneetbehl/plugins/grails-jasper#files/2.0.0.RC1

**Comment by antonioaragon** [comment]
hi, @jmccordova  if you are using grails 3.3.0 be sure to add this to your repositories in your build.gradle  

>      maven { url "http://dl.bintray.com/puneetbehl/plugins" }


this worked for me

**Comment by jmccordova** [comment]
@puneetbehl, I'm using Grails 3.3.0. Looks like I've missed the step given by @antonioaragon. I'll try this on Monday.

**Comment by jmccordova** [comment]
It worked! Thanks, @antonioaragon!

@puneetbehl, I don't know if I've overlooked that step but please add the aforementioned step to the documentation.

`repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
    maven { url "http://dl.bintray.com/puneetbehl/plugins" } //For Jasper Reports
}`

Thanks to the both of you!

**Comment by puneetbehl** [comment]
@jmccordova @antonioaragon  There was an issue with plugin package which has been fixed now. So, you should be able to use this plugin without including ` maven { url "http://dl.bintray.com/puneetbehl/plugins" }`
