### ISSUE TITLE
plugin breaks with grails 3.3.0

### ISSUE THREAD

**Issue by antonioaragon** [puneetbehl/grails-jasper#6]
Hi, I'm using grails version 3.3.0 and I get this error when I try to use the plugin

> java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/ServletRegistrationBean

import org.springframework.boot.context.embedded.ServletRegistrationBean
Does not exist anymore

You need to change the import to
import org.springframework.boot.web.servlet.ServletRegistrationBean

Can you make a change?

**Comment by jmccordova** [comment]
Same! It happens on compile time.

For reference on changes: [https://github.com/spring-projects/spring-boot/issues/8186](url)

**Comment by puneetbehl** [comment]
Published a [v2.1.0.RC1](https://bintray.com/puneetbehl/plugins/jasper/2.1.0.RC1) of the plugin which should be compatible with Grails 3.3.x

**Comment by jmccordova** [comment]
Ooh! It shows no errors now. But I'll keep you updated if there is a bug. Also, will the docs still be the same for this version?
